use vhdl_syntax::syntax::NodeKind;

use crate::props::node_prop::NodeProp;

pub mod node_prop;

pub fn node_kind_prop(kind: NodeKind) -> NodeProp {
    use vhdl_syntax::syntax::NodeKind as Nk;
    match kind {
        // ------- Concurrent Statements -------
        Nk::DeclarationStatementSeparator => NodeProp::newline_before(),
        Nk::BlockHeader => NodeProp::newline_before().indents(),
        Nk::BlockStatement => NodeProp::newline_before(),
        Nk::BlockPreamble => NodeProp::newline_before().space_separated_children(),
        Nk::BlockEpilogue => NodeProp::newline_before().space_separated_children(),
        Nk::CaseGenerateAlternative => NodeProp::newline_before().indents(),
        Nk::CaseGenerateStatement => NodeProp::newline_before(),
        Nk::CaseGenerateStatementEpilogue => NodeProp::newline_before().space_separated_children(),
        Nk::CaseGenerateStatementPreamble => NodeProp::newline_before().space_separated_children(),
        Nk::ComponentInstantiationStatement => NodeProp::newline_before(),
        Nk::ComponentInstantiationItems => NodeProp::nothing_before().indents(),
        Nk::ConcurrentProcedureCallOrComponentInstantiationStatement => NodeProp::newline_before(),
        Nk::ConcurrentAssertionStatement => NodeProp::newline_before().space_separated_children(),
        Nk::ConcurrentSimpleSignalAssignment => {
            NodeProp::newline_before().space_separated_children()
        }
        Nk::ConcurrentConditionalSignalAssignment => {
            NodeProp::newline_before().space_separated_children()
        }
        Nk::ConcurrentSelectedSignalAssignment => {
            NodeProp::newline_before().space_separated_children()
        }
        Nk::ConcurrentSelectedSignalAssignmentPreamble => {
            NodeProp::nothing_before().space_separated_children()
        }
        Nk::ConcurrentStatements => NodeProp::nothing_before().indents(),
        Nk::ForGenerateStatement => NodeProp::newline_before(),
        Nk::ForGenerateStatementEpilogue => NodeProp::newline_before().space_separated_children(),
        Nk::ForGenerateStatementPreamble => NodeProp::newline_before().space_separated_children(),
        Nk::GenerateStatementBody => NodeProp::newline_before().indents(),
        Nk::GenerateStatementBodyEpilogue => NodeProp::newline_before().space_separated_children(),
        Nk::IfGenerateElse => NodeProp::newline_before().space_separated_children(),
        Nk::IfGenerateElsif => NodeProp::newline_before().space_separated_children(),
        Nk::IfGenerateStatement => NodeProp::newline_before(),
        Nk::IfGenerateStatementEpilogue => NodeProp::newline_before().space_separated_children(),
        Nk::IfGenerateStatementPreamble => NodeProp::newline_before().space_separated_children(),
        Nk::ComponentInstantiatedUnit => NodeProp::spaces_before(1).space_separated_children(),
        Nk::EntityInstantiatedUnit => NodeProp::spaces_before(1).space_separated_children(),
        Nk::ConfigurationInstantiatedUnit => NodeProp::spaces_before(1).space_separated_children(),
        Nk::AllSensitivityList => NodeProp::nothing_before(),
        Nk::SensitivityList => NodeProp::nothing_before(),
        Nk::ParenthesizedProcessSensitivityList => NodeProp::new().groups().parenthesized(),
        Nk::ProcessStatement => NodeProp::newline_before(),
        Nk::ProcessStatementEpilogue => NodeProp::newline_before().space_separated_children(),
        Nk::ProcessStatementPreamble => NodeProp::newline_before().space_separated_children(),
        // ------- Declarations -------
        Nk::PackageInstantiationDeclaration => NodeProp::newline_before(),
        Nk::PackageDeclaration => NodeProp::newline_before(),
        Nk::PackageBodyDeclaration => NodeProp::newline_before(),
        Nk::UseClauseDeclaration => NodeProp::newline_before(),
        Nk::ActualPart => NodeProp::new(),
        Nk::AliasDeclaration => NodeProp::newline_before().space_separated_children(),
        Nk::AssociationElement => NodeProp::nothing_before().space_separated_children(),
        Nk::AssociationList => NodeProp::nothing_before().groups().indents(),
        Nk::ParenthesizedAssociationList => NodeProp::nothing_before().parenthesized(),
        Nk::AttributeDeclaration => NodeProp::newline_before().space_separated_children(),
        Nk::ComponentDeclaration => NodeProp::newline_before(),
        Nk::ComponentDeclarationEpilogue => NodeProp::newline_before().space_separated_children(),
        Nk::ComponentDeclarationItems => NodeProp::nothing_before().indents(),
        Nk::ComponentDeclarationPreamble => NodeProp::newline_before().space_separated_children(),
        Nk::ConstantDeclaration => NodeProp::newline_before().space_separated_children(),
        Nk::RangeConstraintConstraint => NodeProp::nothing_before(),
        Nk::ResolutionIndicationElementResolution => NodeProp::nothing_before(),
        Nk::RecordResolutionElementResolution => NodeProp::nothing_before(),
        Nk::EntityClassEntry => NodeProp::nothing_before(),
        Nk::EntityClassEntryList => NodeProp::nothing_before().indents(),
        Nk::ParenthesizedEntityClassEntryList => NodeProp::nothing_before().groups().parenthesized(),
        Nk::FileDeclaration => NodeProp::newline_before().space_separated_children(),
        Nk::FileOpenInformation => NodeProp::new().space_separated_children(),
        Nk::FormalPart => NodeProp::new(),
        Nk::FullTypeDeclaration => NodeProp::newline_before().space_separated_children(),
        Nk::GenericClause => NodeProp::newline_before().space_separated_children(),
        Nk::GenericMapAspect => NodeProp::newline_before().space_separated_children(),
        Nk::SemiColonTerminatedGenericMapAspect => NodeProp::new(),
        Nk::GroupConstituentList => NodeProp::new(),
        Nk::ParenthesizedGroupConstituentList => NodeProp::new().groups().parenthesized(),
        Nk::GroupDeclaration => NodeProp::newline_before().space_separated_children(),
        Nk::GroupTemplateDeclaration => NodeProp::newline_before().space_separated_children(),
        Nk::InterfaceConstantDeclaration => NodeProp::new().space_separated_children(),
        Nk::InterfaceFileDeclaration => NodeProp::new().space_separated_children(),
        Nk::InterfaceFunctionSpecification => NodeProp::new().space_separated_children(),
        Nk::InterfaceIncompleteTypeDeclaration => NodeProp::new().space_separated_children(),
        Nk::InterfaceList => NodeProp::new().indents().groups().soft_break_after(0),
        Nk::ParenthesizedInterfaceList => NodeProp::new().groups().parenthesized(),
        Nk::InterfacePackageDeclaration => NodeProp::new(),
        Nk::InterfacePackageDeclarationPreamble => NodeProp::new().space_separated_children(),
        Nk::InterfacePackageGenericMapAspect => NodeProp::new().space_separated_children(),
        Nk::ParenthesizedInterfacePackageGenericMapAspectInner => {
            NodeProp::new().groups().parenthesized()
        }
        Nk::InterfacePackageGenericMapAspectAssociations => NodeProp::new(),
        Nk::InterfacePackageGenericMapAspectBox => NodeProp::new(),
        Nk::InterfacePackageGenericMapAspectDefault => NodeProp::new(),
        Nk::InterfaceProcedureSpecification => NodeProp::new().space_separated_children(),
        Nk::InterfaceSignalDeclaration => NodeProp::new().space_separated_children(),
        Nk::InterfaceSubprogramDeclaration => NodeProp::new().space_separated_children(),
        Nk::InterfaceSubprogramDefaultBox => NodeProp::new(),
        Nk::InterfaceSubprogramDefaultName => NodeProp::new(),
        Nk::InterfaceVariableDeclaration => NodeProp::new().space_separated_children(),
        Nk::PortClause => NodeProp::newline_before().space_separated_children(),
        Nk::PortMapAspect => NodeProp::newline_before().space_separated_children(),
        Nk::SemiColonTerminatedPortMapAspect => NodeProp::new(),
        Nk::RecordElementResolution => NodeProp::new().space_separated_children(),
        Nk::RecordResolution => NodeProp::new(),
        Nk::NameResolutionIndication => NodeProp::new(),
        Nk::ElementResolutionResolutionIndication => NodeProp::new(),
        Nk::ParenthesizedElementResolutionResolutionIndication => {
            NodeProp::new().groups().parenthesized()
        }
        Nk::SignalDeclaration => NodeProp::newline_before().space_separated_children(),
        Nk::SubtypeDeclaration => NodeProp::newline_before().space_separated_children(),
        Nk::SubtypeIndication => NodeProp::new(),
        Nk::VariableDeclaration => NodeProp::newline_before().space_separated_children(),
        Nk::SharedVariableDeclaration => NodeProp::newline_before().space_separated_children(),
        Nk::Declarations => NodeProp::new().indents(),
        // ------- Design Entities -------
        Nk::ArchitectureBody => NodeProp::new(),
        Nk::ArchitecturePreamble => NodeProp::newline_before().space_separated_children(),
        Nk::ArchitectureEpilogue => NodeProp::newline_before().space_separated_children(),
        Nk::BlockConfigurationItem => NodeProp::new(),
        Nk::BlockConfigurationItems => NodeProp::new().indents(),
        Nk::BlockConfiguration => NodeProp::newline_before(),
        Nk::BlockConfigurationEpilogue => NodeProp::newline_before().space_separated_children(),
        Nk::BlockConfigurationPreamble => NodeProp::newline_before().space_separated_children(),
        Nk::ComponentConfiguration => NodeProp::new(),
        Nk::ComponentConfigurationEpilogue => NodeProp::newline_before().space_separated_children(),
        Nk::ComponentConfigurationItems => NodeProp::new().indents(),
        Nk::ComponentConfigurationPreamble => NodeProp::newline_before().space_separated_children(),
        Nk::ConfigurationDeclaration => NodeProp::new(),
        Nk::ConfigurationDeclarationEpilogue => {
            NodeProp::newline_before().space_separated_children()
        }
        Nk::ConfigurationDeclarationItems => NodeProp::new().indents(),
        Nk::ConfigurationDeclarationPreamble => {
            NodeProp::newline_before().space_separated_children()
        }
        Nk::EntityDeclaration => NodeProp::new(),
        Nk::EntityDeclarationEpilogue => NodeProp::newline_before().space_separated_children(),
        Nk::EntityDeclarationPreamble => NodeProp::newline_before().space_separated_children(),
        Nk::EntityHeader => NodeProp::new().indents(),
        // ------- Design Units -------
        Nk::ContextClause => NodeProp::new(),
        Nk::ContextDeclaration => NodeProp::new(),
        Nk::ContextDeclarationEpilogue => NodeProp::newline_before(),
        Nk::ContextDeclarationPreamble => NodeProp::newline_before().space_separated_children(),
        Nk::UseClauseContextItem => NodeProp::new(),
        Nk::ContextReference => NodeProp::new().space_separated_children(),
        Nk::DesignFile => NodeProp::new(),
        Nk::DesignUnit => NodeProp::new(),
        Nk::LibraryClause => NodeProp::new().space_separated_children(),
        Nk::PrimaryUnitPackageDeclaration => NodeProp::new(),
        Nk::PackageInstantiationDeclarationPrimaryUnit => NodeProp::new(),
        Nk::SecondaryUnitPackageBody => NodeProp::new(),
        // ------- Expression -------
        Nk::ParenthesizedExpression => NodeProp::new().groups().parenthesized(),
        Nk::ParenthesizedExpressionOrAggregate => NodeProp::new(),
        Nk::UnaryExpression => NodeProp::new(),
        Nk::BinaryExpression => NodeProp::new().space_separated_children(),
        Nk::LiteralExpression => NodeProp::new(),
        Nk::PhysicalLiteralExpression => NodeProp::new(),
        Nk::NameExpression => NodeProp::new(),
        Nk::Aggregate => NodeProp::new(),
        Nk::SubtypeIndicationAllocator => NodeProp::new(),
        Nk::ExpressionAllocator => NodeProp::new().space_separated_children(),
        Nk::OthersChoice => NodeProp::new(),
        Nk::ExpressionChoice => NodeProp::new(),
        Nk::DiscreteRangeChoice => NodeProp::new(),
        Nk::Choices => NodeProp::new(),
        Nk::ElementAssociation => NodeProp::new(),
        Nk::QualifiedExpression => NodeProp::new(),
        Nk::TypeConversion => NodeProp::new(),
        // ------- Namers -------
        Nk::AbsolutePathname => NodeProp::new(),
        Nk::AttributeName => NodeProp::new(),
        Nk::ExternalConstantName => NodeProp::new(),
        Nk::ExternalSignalName => NodeProp::new(),
        Nk::ExternalVariableName => NodeProp::new(),
        Nk::PackagePathname => NodeProp::new(),
        Nk::RelativePathname => NodeProp::new(),
        Nk::PartialPathname => NodeProp::new(),
        Nk::NameList => NodeProp::new(),
        Nk::Label => NodeProp::new(),
        Nk::Name => NodeProp::new(),
        Nk::NameDesignatorPrefix => NodeProp::new(),
        Nk::SelectedName => NodeProp::new(),
        Nk::ParenthesizedName => NodeProp::new().groups().parenthesized(),
        Nk::RawTokens => NodeProp::new(),
        // ------- PSL -------
        Nk::PslClockDeclaration => NodeProp::newline_before(),
        Nk::PslDirective => NodeProp::newline_before(),
        Nk::PslPropertyDeclaration => NodeProp::newline_before(),
        Nk::PslSequenceDeclaration => NodeProp::newline_before(),
        Nk::PslVerificationUnit => NodeProp::new(),
        // ------- Scope and Visibility -------
        Nk::UseClause => NodeProp::newline_before().space_separated_children(),
        // ------- Sequential Statements -------
        Nk::Assertion => NodeProp::new().space_separated_children(),
        Nk::AssertionStatement => NodeProp::newline_before().space_separated_children(),
        Nk::CaseStatementAlternative => NodeProp::newline_before()
            .indents()
            .space_separated_children(),
        Nk::CaseStatementAlternativePreamble => NodeProp::new().space_separated_children(),
        Nk::CaseStatement => NodeProp::newline_before(),
        Nk::CaseStatementEpilogue => NodeProp::newline_before().space_separated_children(),
        Nk::CaseStatementPreamble => NodeProp::newline_before().space_separated_children(),
        Nk::ConditionClause => NodeProp::new().space_separated_children(),
        Nk::ConditionalElseWhenExpression => NodeProp::new().space_separated_children(),
        Nk::ConditionalElseItem => NodeProp::new().space_separated_children(),
        Nk::ConditionalExpressions => NodeProp::new(),
        Nk::ConditionalExpression => NodeProp::new().space_separated_children(),
        Nk::ConditionalForceAssignment => NodeProp::new().space_separated_children(),
        Nk::ConditionalVariableAssignment => NodeProp::newline_before().space_separated_children(),
        Nk::ConditionalWaveformAssignment => NodeProp::new().space_separated_children(),
        Nk::ConditionalWaveformElseWhenExpression => NodeProp::new().space_separated_children(),
        Nk::ConditionalWaveformElseItem => NodeProp::new().space_separated_children(),
        Nk::ConditionalWaveforms => NodeProp::new(),
        Nk::ConditionalWaveform => NodeProp::new().space_separated_children(),
        Nk::TransportDelayMechanism => NodeProp::new(),
        Nk::InertialDelayMechanism => NodeProp::new().space_separated_children(),
        Nk::ExitStatement => NodeProp::newline_before(),
        Nk::IfStatement => NodeProp::newline_before(),
        Nk::IfStatementElse => NodeProp::newline_before().space_separated_children(),
        Nk::IfStatementElsif => NodeProp::newline_before().space_separated_children(),
        Nk::IfStatementEpilogue => NodeProp::newline_before().space_separated_children(),
        Nk::IfStatementPreamble => NodeProp::newline_before().space_separated_children(),
        Nk::WhileIterationScheme => NodeProp::new().space_separated_children(),
        Nk::ForIterationScheme => NodeProp::new().space_separated_children(),
        Nk::LoopStatement => NodeProp::newline_before(),
        Nk::LoopStatementEpilogue => NodeProp::newline_before().space_separated_children(),
        Nk::LoopStatementPreamble => NodeProp::newline_before().space_separated_children(),
        Nk::NextStatement => NodeProp::newline_before().space_separated_children(),
        Nk::NullStatement => NodeProp::newline_before().space_separated_children(),
        Nk::ParameterSpecification => NodeProp::new().space_separated_children(),
        Nk::ProcedureCallStatement => NodeProp::newline_before().space_separated_children(),
        Nk::ReportStatement => NodeProp::newline_before().space_separated_children(),
        Nk::ReturnStatement => NodeProp::newline_before().space_separated_children(),
        Nk::SelectedExpressionItem => NodeProp::new().space_separated_children(),
        Nk::SelectedExpressions => NodeProp::new(),
        Nk::SelectedForceAssignment => NodeProp::new().space_separated_children(),
        Nk::SelectedWaveformItem => NodeProp::new().space_separated_children(),
        Nk::SelectedWaveforms => NodeProp::new(),
        Nk::SelectedVariableAssignment => NodeProp::newline_before(),
        Nk::SelectedWaveformAssignment => NodeProp::new().space_separated_children(),
        Nk::SelectedAssignmentPreamble => NodeProp::new().space_separated_children(),
        Nk::SensitivityClause => NodeProp::new().space_separated_children(),
        Nk::SimpleForceAssignment => NodeProp::newline_before(),
        Nk::SimpleReleaseAssignment => NodeProp::new().space_separated_children(),
        Nk::SimpleWaveformAssignment => NodeProp::newline_before(),
        Nk::SimpleVariableAssignment => NodeProp::newline_before().space_separated_children(),
        Nk::NameTarget => NodeProp::new(),
        Nk::AggregateTarget => NodeProp::new(),
        Nk::TimeoutClause => NodeProp::new(),
        Nk::WaitStatement => NodeProp::newline_before().space_separated_children(),
        Nk::WaveformElement => NodeProp::new().space_separated_children(),
        Nk::WaveformElements => NodeProp::new(),
        Nk::UnaffectedWaveform => NodeProp::new(),
        Nk::SequentialStatements => NodeProp::new().indents(),
        // ------- Specifications -------
        Nk::AttributeSpecification => NodeProp::newline_before().space_separated_children(),
        Nk::BindingIndication => NodeProp::new().space_separated_children(),
        Nk::SemiColonTerminatedBindingIndication => NodeProp::newline_before(),
        Nk::ComponentSpecification => NodeProp::new().space_separated_children(),
        Nk::CompoundConfigurationSpecification => NodeProp::newline_before(),
        Nk::CompoundConfigurationSpecificationItems => NodeProp::new().indents(),
        Nk::DisconnectionSpecification => NodeProp::newline_before().space_separated_children(),
        Nk::EntityEntityAspect => NodeProp::new().space_separated_children(),
        Nk::EntityConfigurationAspect => NodeProp::new().space_separated_children(),
        Nk::EntityOpenAspect => NodeProp::new(),
        Nk::EntityDesignator => NodeProp::new(),
        Nk::EntityDesignatorList => NodeProp::new(),
        Nk::EntityNameListAll => NodeProp::new(),
        Nk::EntityNameListOthers => NodeProp::new(),
        Nk::EntitySpecification => NodeProp::new().space_separated_children(),
        Nk::GuardedSignalSpecification => NodeProp::new().space_separated_children(),
        Nk::InstantiationListList => NodeProp::new(),
        Nk::InstantiationListAll => NodeProp::new(),
        Nk::InstantiationListOthers => NodeProp::new(),
        Nk::SignalListList => NodeProp::new(),
        Nk::SignalListAll => NodeProp::new(),
        Nk::SignalListOthers => NodeProp::new(),
        Nk::SimpleConfigurationSpecification => NodeProp::newline_before(),
        Nk::VerificationUnitBindingIndication => NodeProp::new().space_separated_children(),
        Nk::SemiColonTerminatedVerificationUnitBindingIndication => NodeProp::newline_before(),
        Nk::VerificationUnitList => NodeProp::new(),
        // ------- Subprogram and Packages -------
        Nk::SubprogramDeclaration => NodeProp::newline_before(),
        Nk::SubprogramBody => NodeProp::newline_before(),
        Nk::SubprogramBodyEpilogue => NodeProp::newline_before().space_separated_children(),
        Nk::SubprogramBodyPreamble => NodeProp::newline_before().space_separated_children(),
        Nk::SubprogramHeader => NodeProp::new(),
        Nk::SubprogramHeaderGenericClause => NodeProp::new(),
        Nk::SubprogramInstantiationDeclaration => {
            NodeProp::newline_before().space_separated_children()
        }
        Nk::SubprogramInstantiationDeclarationPreamble => {
            NodeProp::new().space_separated_children()
        }
        Nk::ProcedureSpecification => NodeProp::new(),
        Nk::FunctionSpecification => NodeProp::new(),
        Nk::ParameterList => NodeProp::new(),
        Nk::Package => NodeProp::new(),
        Nk::PackageBody => NodeProp::newline_before(),
        Nk::PackageBodyEpilogue => NodeProp::newline_before(),
        Nk::PackageBodyPreamble => NodeProp::newline_before().space_separated_children(),
        Nk::PackageEpilogue => NodeProp::newline_before().space_separated_children(),
        Nk::PackageHeader => NodeProp::new().indents(),
        Nk::PackageInstantiation => NodeProp::new().space_separated_children(),
        Nk::PackageInstantiationPreamble => NodeProp::new().space_separated_children(),
        Nk::PackagePreamble => NodeProp::newline_before().space_separated_children(),
        Nk::Signature => NodeProp::new(),
        // ------- Types -------
        Nk::AccessTypeDefinition => NodeProp::new(),
        Nk::ArrayConstraint => NodeProp::new(),
        Nk::ConstrainedArrayDefinition => NodeProp::new(),
        Nk::SubtypeIndicationDiscreteDiscreteRange => NodeProp::new(),
        Nk::SubtypeIndicationDiscreteRange => NodeProp::new(),
        Nk::OpenDiscreteRange => NodeProp::new(),
        Nk::ElementDeclaration => NodeProp::newline_before(),
        Nk::EnumerationTypeDefinition => NodeProp::new(),
        Nk::EnumerationTypeDefinitionItems => {
            NodeProp::new().indents().groups().soft_break_after(0)
        }
        Nk::ParenthesizedEnumerationTypeDefinitionItems => NodeProp::new().groups().parenthesized(),
        Nk::FileTypeDefinition => NodeProp::new(),
        Nk::IdentifierList => NodeProp::new(),
        Nk::IncompleteTypeDeclaration => NodeProp::newline_before(),
        Nk::IndexSubtypeDefinition => NodeProp::new(),
        Nk::PhysicalLiteral => NodeProp::new(),
        Nk::PhysicalTypeDefinition => NodeProp::new(),
        Nk::PhysicalTypeDefinitionEpilogue => NodeProp::newline_before(),
        Nk::UnitDeclarations => NodeProp::new().indents(),
        Nk::PrimaryUnitDeclaration => NodeProp::newline_before(),
        Nk::ProtectedTypeBody => NodeProp::new(),
        Nk::ProtectedTypeBodyEpilogue => NodeProp::newline_before(),
        Nk::ProtectedTypeBodyPreamble => NodeProp::newline_before(),
        Nk::ProtectedTypeDeclaration => NodeProp::new(),
        Nk::ProtectedTypeDeclarationEpilogue => NodeProp::newline_before(),
        Nk::ProtectedTypeDeclarationPreamble => NodeProp::newline_before(),
        Nk::RangeExpression => NodeProp::new().space_separated_children(),
        Nk::AttributeRange => NodeProp::new(),
        Nk::RangeConstraint => NodeProp::new(),
        Nk::RecordConstraint => NodeProp::new(),
        Nk::RecordConstraintItems => NodeProp::new().indents().groups().soft_break_after(0),
        Nk::ParenthesizedRecordConstraintItems => NodeProp::new().groups().parenthesized(),
        Nk::RecordElementConstraint => NodeProp::new(),
        Nk::RecordTypeDefinition => NodeProp::new(),
        Nk::RecordTypeDefinitionEpilogue => NodeProp::newline_before(),
        Nk::RecordTypeDefinitionPreamble => NodeProp::newline_before(),
        Nk::RecordElementDeclarations => NodeProp::new().indents().groups(),
        Nk::NumericTypeDefinition => NodeProp::new(),
        Nk::SecondaryUnitDeclaration => NodeProp::newline_before(),
        Nk::IndexConstraint => NodeProp::new(),
        Nk::IndexConstraintItems => NodeProp::new().indents().groups().soft_break_after(0),
        Nk::ParenthesizedIndexConstraintItems => NodeProp::new().groups().parenthesized(),
        Nk::IndexSubtypeDefinitionList => NodeProp::new(),
        Nk::ParenthesizedIndexSubtypeDefinitionList => NodeProp::new().groups().parenthesized(),
        Nk::UnboundedArrayDefinition => NodeProp::new(),
    }
}
