# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2018, Olof Kraigher olof.kraigher@gmail.com

[package]
name = "vhdl_lang"
version = "0.80.0"
authors = ["Olof Kraigher <olof.kraigher@gmail.com>"]
license = "MPL-2.0"
description = "VHDL Language Frontend"
repository = "https://github.com/kraigher/rust_hdl"
edition = "2021"

[dependencies]
vhdl_lang_macros = { version = "^0.80.0", path = "../vhdl_lang_macros" }
pad = "0"
fnv = "1"
clap = { version = "4", features = ["derive"] }
toml = "0"
glob = "0"
dirs = "5"
rayon = "1"
parking_lot = "0"
dunce = "1"
pinned_vec = "0"
itertools = "0"
subst = "0.3.0"
strum = { version = "0.26.2", features = ["derive"] }
enum-map = "2.7.3"

[dev-dependencies]
tempfile = "3"
pretty_assertions = "1"
assert_matches = "1"
brunch = "0"

[[bench]]
name = "benchmark"
harness = false

[features]
default = []
